### ISSUE TITLE
Pledbrook has not supplied an email address

### ISSUE THREAD

**Issue by olivermt** [grails/grails-howtos#1]
So... we can't message you.

I'd like commit access though!

Edit:

For referential reasons; I'm Oliver Tynes from the mailinglist/freenode.

**Comment by vithun** [comment]
Had the same problem myself. However you can compose a message to Peter (pledbrook) if you go to the 'notifications' section of GitHub.

**Comment by pledbrook** [comment]
I blame this on GitHub. I have no idea why their "Message" button uses email rather than the internal messaging system. Very confusing. Anyway, I'll add you now.
